---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400

...
