---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: Create a directory if it does not exist
      file:
       path: /var/www
       state: directory
       mode: '0755'

...
